<?php

/**
 * @file
 */

 /**
  * Install config with enabled locations in groupexpro
  */
function openy_pef_gxp_sync_update_8001() {
    $path = drupal_get_path('module', 'openy_pef_gxp_sync') . '/config/install/';
    $config_importer = \Drupal::service('config_import.importer');
    $config_importer->setDirectory($path);
    $config_importer->importConfigs(
      ['openy_pef_gxp_sync.enable_locations']
    );
 }
